'''
format per item in problems is [difficulty, area, source, problem, answer]

difficulty (int from 0 to 5)
- easy, average, difficult respectively
area (str, either 'A', 'C', 'G', 'N', or 'M')
- alg, combi, geo, nt, misc
type (str, either 'S' or 'P')
- short answer or proof
source (str)
- preferred format: Contest Yr Round / No
problem (str)
- format in latex
answer (str)
- format in latex
- if proof question then write the proof lol :)

other notes
- amsmath, amssymb, amsthm, and asymptote packages are imported so you may use those
- every math mode is in display style
- use \\ for backslash
'''

problems = [
    [0, 'N', 'S', 'PMO 2024 Qualifying / I.1', 'Let $a,b,c$ be positive integers such that $$3.14=a+\\frac1{b+\\frac1c}.$$ What is $a+b+c?$', '17'],
    [0, 'G', 'S', 'PMO 2024 Qualifying / I.2', 'What is the area of a rhombus whose diagonals have length 14 and 48, respectively?', '336'],
    [1, 'A', 'S', 'PMO 2024 Quailfying / I.3', 'The arithmetic mean of 11 integers is 10. After adding 20 to each of the first four and subtracting 24 from each of the last seven, what is the new mean?', '2'],
    [1, 'N', 'S', 'PMO 2024 Qualifying / I.4', 'Let $a$ and $b$ be the last two digits of the 5-digit number $\\overline{764ab}$. What is the largest possible value of the product of $ab^2$ if the 5-digit number is divisible by 6?', '512'],
    [1, 'C', 'S', 'PMO 2024 Qualifying / I.5', 'An urn contains two white and two black balls. John draws two balls simultaneously from the urn. If the balls are of different colors, he stops. Otherwise, he returns both balls to the urn and then repeats the process. What is the probability that he stops after exactly three draws?', '$\\frac{2}{27}$'],
    [2, 'N', 'S', 'PMO 2024 Qualifying / II.1', 'Today --- the 2nd day of the 12th month of the year 2023 --- marks the start of the 26th Philippine Mathematical Olympiad. What is the remainder when $2023^{12^2}$ is divided by 26?', '1'],
    [2, 'A', 'S', 'PMO 2024 Qualifying / II.2', 'There are 2024 coins laid out in a row. For some positive integer $x$, at least $\\frac23$ of the first $x$ coins are heads, and at least $\\frac45$ of the last $x$ coins are tails. What is the maximum possible value of $x$?', '1380'],
    [2, 'N', 'S', 'PMO 2024 Qualifying / II.3', 'Find the remainder when $\\sum^{2023}_{n=1}2023^n$ is divided by 15.', '4'],
    [2, 'N', 'S', 'Mathleague 12300 HS Relay / 1-1', 'Let $K$ be the number of prime numbers $p$ such that $p$ is a factor of $(T+1)!$, but $p^2$ is not. Find $K$.', '2'],
    [1, 'N', 'S', 'Mathleague 12300 HS Relay / 3-1', 'Let $K$ be the 65th digit after the decimal point in the decimal expansion of $\\frac1{17}$. Find $K$.', '0'],
    [2, 'G', 'S', 'Sipnayan 2023 JHS Semifinals / E1', 'What is the area of a regular dodecagon (a 12-sided polygon) inscribed in a circle of diameter 12?', '108'],
    [2, 'N', 'S', 'Sipnayan 2023 JHS Semifinals / E2', 'Find the last two digits of $76^{2023^{2023}}.$', '76'],
    [2, 'G', 'S', 'Sipnayan 2023 JHS Semifinals / E3\\footnote{Modified without diagram.}', 'A figure is constructed starting with a circle of radius 10. Its inscribed equilateral triangle is drawn, and then the triangle\'s incircle is added. This process is repeated to infinity. Find the sum of the radii of the circles.', '20'],
    [2, 'G', 'S', 'Sipnayan 2023 JHS Semifinals / E4\\footnote{Modified without diagram.}', 'The circle $O$ has diameter $AB=12.$ Let $C$ be a point outside the circle such that $ABC$ is an equilateral triangle. If the area of the shaded region is of the form $X\sqrt3+Y\pi$ for some positive integers $X$ and $Y,$ what is $X+Y?$', '24'],
    [1, 'C', 'S', 'Sipnayan 2023 JHS Semifinals / E5', 'What is the least number of colors needed to color a $100\\times100$ chessboard such that no two vertically, horizontally, and diagonally adjacent squares have the same color?', '4'],
    [3, 'G', 'S', 'Sipnayan 2023 JHS Semifinals / A1', 'The regular hexagon $ABCDEF$ is inscribed in a circle of radius $4\\sqrt[4]{3}.$ Let $G$ be a point on $DE$ such that $DG:GE=3:1.$ What is the area of pentagon $ABGEF?$', '42'],
    [2, 'N', 'S', 'Sipnayan 2023 JHS Semifinals / A2', 'Let $X$ be the product of all odd integers from 1 to 49, inclusive. What are the last three digits of $X?$', '625'],
    [3, 'A', 'S', 'Sipnayan 2023 JHS Semifinals / A3', 'Let $$P(x)=x^6+x^5+x^4+x^3+x^2+x+1$$ and $D(x)=x^2-1.$ If the remainder of $P(x)$ when divided by $D(x)$ is $R(x),$ what is $R(100)?$', '304'],
    [2, 'A', 'S', 'Sipnayan 2023 JHS Semifinals / A4', 'Anna the Anaconda can clean her burrow in $x$ hours, while Sally the Spider can do the same in $y$ hours. If they can finish cleaning it together in $4$ hours, and $x$ and $y$ are positive integers, then what is the largest possible value of $x+y?$', '25'],
    [2, 'C', 'S', 'Sipnayan 2023 JHS Semifinals / A5', 'Basti the Beaver has 10 children, called kits, that are sitting in a circle. He wants to make them play with each other, so he will be giving then four toys such that each kit will have at most one toy and that no adjacent kits both have toys. How many ways can Basti give the toys?', '420'],
    [3, 'G', 'S', 'Sipnayan 2023 JHS Semifinals / D1', 'The regular tetrahedron $ABCD$ has side length $10\sqrt6$ cm. If the radius of its inscribed sphere is $r$ and the radius of its circumscribed sphere is $R,$ what is $(R-r),$ in centimeters?', '10'],
    [4, 'A', 'S', 'Sipnayan 2023 JHS Semifinals / D2', 'Let the function $g$ satisfy the equation $$(2023^3)g(-x)-x^3g\left(\\frac1x\\right)=-54x^3$$ for all nonzero real numbers $x.$ What is $g(2023)?$', '54'],
    [3, 'N', 'S', 'Sipnayan 2023 JHS Semifinals / D3', 'If $x>6,$ where $x$ is a positive integer, then what is the smallest possible value of $x$ such that $x(x-5)$ leaves a remainder of $6$ when divided by $36?$', '15'],
    [4, 'G', 'S', 'Sipnayan 2023 JHS Semifinals / D4\\footnote{Modified without diagram.}', 'A paper in the shape of an equilateral triangle with side length 60 is folded such that $AB=12.$ If $r$ is the radius of the incircle of $\\triangle BDE,$ what is $r^2?$', '48'],
    [2, 'G', 'S', 'Sipnayan 2023 JHS Semifinals / D5\\footnote{Modified without diagram.}', 'In $\\triangle ABC$ with angle bisector $BD,$ $AB=9$ and $AD=6.$ If its perimeter is 35, find the length of $BC.$', '12'],
    [2, 'N', 'S', 'PMO 2024 Qualifying / II.4', 'The integers from 1 to 2023 are written on a long blackboard in a straight line. Nillie colors any number divisible by 23 in blue, any number divisibility by 88 in yellow, any number divisible by both 23 and 88 in green, and any number not divisible by either in red. How many adjacent pairs of numbers have different colors?', '216'],
    [2, 'A', 'S', 'PMO 2024 Qualifying / II.5', 'Let $r$ and $s$ of the polynomial $x^2+2x+3$. What is the value of $\\frac1{r^2-1}+\\frac1{s^2-1}$?', '$-\\frac13$'],
    [3, 'A', 'S', 'Mathleague 12300 HS Relay / 4-2', 'The graph of the equation $x^2-64=2(x+8)(y-20)$ consists of two lines in the coordinate plane. Let $K$ be the $y$-coordinate of the point where these two lines intersect. Find $K$.', '12'],
    [3, 'A', 'S', 'Sipnayan 2019 JHS Semifinals B / A4', 'Given that $\\sin2\\theta=-\\frac15$, find $\\sin^6\\theta+\\cos^6\\theta.$ Express the answer in lowest terms.', '$\\frac{97}{100}$'],
    [3, 'A', 'S', 'Sipnayan 2023 JHS Written / A5', 'Evaluate $$\\sum^{200}_{i=1}\\sin^2\\left[\\frac{(2i-1)\\pi}{8}\\right].$$', '100'],
    [3, 'A', 'P', 'USAMO 1978 / 1\\footnote{Modified wording.}', 'The sum of 5 real numbers is 8 and the sum of their squares is 16. Determine, with proof, the largest possible value for one of the numbers', 'Let the five numbers be $a,b,c,d,e$. Then, we have $a+b+c+d+e=8$ and $a^2+b^2+c^2+d^2+e^2=16$, so $b+c+d+e=8-a$ and $b^2+c^2+d^2+e^2=16-a^2$. Thus, by the Cauchy-Schwarz inequality, we have $$(b+c+d+e)^2\\le(1+1+1+1)(b^2+c^2+d^2+e^2),$$ so $(8-a)^2\\le4(16-a^2)$, or $5a^2-16a\\le0$. Therefore, $e\in\\left[0,\\frac{16}5\\right]$, so $e\\le\\boxed{\\frac{16}{5}}.$'],
    [3, 'G', 'S', 'AMC 12 2006 / 23', 'Isosceles $\\triangle{ABC}$ has a right angle at $C$. Point $P$ is inside $\\triangle{ABC}$, such that $PA=11$, $PB=7$, and $PC=6$. Legs $\overline{AC}$ and $\overline{BC}$ have length $s=\sqrt{a+b\sqrt{2}}$, where $a$ and $b$ are positive integers. What is $a+b$?\n\\begin{center}\n\\begin{asy}\nsize(4cm);pair A,B,C,P;A=(10,0);B=(0,10);C=(0,0);P=(3,3.5);draw(A--B--C--cycle,linewidth(0.7));draw(A--P,linewidth(0.7));draw(B--P--C,linewidth(0.7));label("$A$",A,E);label("$B$",B,N);label("$C$",C,S);label("$P$",P,NE);label("7",(1.5,6.75),E);label("6",(1.5, 1.75),E);label("11",(6.5,1.75),S);\n\\end{asy}\n\\end{center}', '127'],
    [2, 'A', 'S', 'T. Andreescu, \\textit{105 Algebra Problems}, Chapter 2', 'If $a$ is a real number such that $a-\\frac1a=2,$ find $a^4+\\frac1{a^4}.$', '7'],
    [3, 'A', 'S', 'T. Andreescu, \\textit{105 Algebra Problems}, Chapter 2', 'Find all pairs $(x,y)$ of real numbers such that $$4x^2+9y^2+1=12(x+y-1).$$', '$\\left(\\frac32,\\frac23\\right)$'],
    [4, 'A', 'P', 'Y. Chen, \\textit{Problem Solving Using Vieta\'s Theorem}', 'If all coefficients of the polynomial $$f(x)=a_nx^n+a_{n-1}x^{n-1}+\\dots+a_3x^3+x^2+x+1$$ are real numbers, prove that its roots cannot be all real.', 'Let $r_1,r_2,\\dots,r_n$ be the roots of $f(x)$. Then, $$a_n+\\frac{a-1}x+\\frac{a-2}{x^2}+\\dots+\\frac1{x^{n-2}}+\\frac1{x^{n-1}}+\\frac1{x^n}=0.$$ Now, let $y=\\frac1x$. Then, $$g(y)=y^n+y^{n-1}+y^{n-2}+\dots+a_{n-1}y+a_n=0.$$ Since $r_1,r_2,\\dots,r_n$ are the roots of $f(x)$, we know that $\\frac1{r_1},\\frac1{r_2},\\dots,\\frac1{r_n}$ are the roots of $g(y)$. Thus, $$\\frac1{r_1}+\\frac1{r_2}+\\dots+\\frac1{r_n}=-1$$ and $$\\frac1{r_1r_2}+\\frac1{r_1r_3}+\\dots+\\frac1{r_{n-1}r_n}=1,$$ hence $$\\left(\\frac1{r_1}\\right)^2+\\left(\\frac1{r_2}\\right)^2+\\dots+\\left(\\frac1{r_n}\\right)^2=(-1)^2-2(1)=-1<0,$$ contradiction. Therefore, not all of $\\frac1{r_1},\\frac1{r_2},\\dots,\\frac1{r_n}$ are real, so not all roots of $f(x)$ are real. $\\square$'],
    [4, 'G', 'P', 'CGMO 2012 / 5\\footnote{Modified without diagram.}', 'Let $ABC$ be a triangle. The incircle of $ABC$ is tangent to sides $AB$ and $AC$ at $D$ and $E$ respectively, and $O$ is the circumcenter of $BCI$. Prove that $\\angle ODB = \\angle OEC$.', 'Since $O$ is the center of $(B I C)$, $O$ is the intersection of $\\overline{A I}$ and $(A B C)$ by the Incenter/Excenter Lemma. Since $\\angle D A O=\\angle E A O, A O=A O$, and $A D=A E$, we have that $\\triangle D A O \cong \\triangle E A O$ by SAS Congruence, so $\\angle A D O=\\angle A E O$. Hence, $\\angle O D B=180^{\circ}-\\angle A D O=180^{\circ}-\\angle A E O =\\angle O E C.$ $\\square$'],
    [3, 'C', 'S', 'PMO 2024 Areas / I.10', 'Fern writes down all integers from 1 to 999 that do not contain the digit 2, in increasing order. Stark writes down all integers from 1 to 999 that do not contain the digit 6, in increasing order. How many numbers are written in both of their lists, in the same position?', '124'],
    [3, 'G', 'S', 'PMO 2024 Areas / I.8\\footnote{Modified wording and diagram.}', 'A circular sector has central angle $60^\\circ$. A smaller circle is inscribed in the sector, tangent to the two radii and the arc; a larger circle is circumscribed about the same sector as shown below. If the area of the region inside the large circle and outside the small circle is equal to 2024, find the remainder when the area of the smaller circle is divided by 1000.\n\\begin{center}\n\\begin{asy}\nimport graph; size(4.cm); real lsf=0.5; pen dps=linewidth(0.7)+fontsize(10); defaultpen(dps); pen ds=black; real xmin=5.,xmax=15.,ymin=-7.,ymax=4.; draw(shift((10.,2.92820323027551))*xscale(8.)*yscale(8.)*arc((0,0),1,240.,300.)--(10.,2.92820323027551)--cycle,linewidth(2.)); draw(circle((10.,-1.6905989232414953),4.618802153517006),linewidth(2.)); draw(circle((10.,-2.405130103057825),2.666666666666666),linewidth(2.)); clip((xmin,ymin)--(xmin,ymax)--(xmax,ymax)--(xmax,ymin)--cycle); \n\\end{asy}\n\\end{center}', '12'],
    [4, 'A', 'P', 'Brazil 2020 / 1', 'Prove that there are positive integers $a_1, a_2,\\dots, a_{2020}$ such that $$\\dfrac{1}{a_1}+\\dfrac{1}{2a_2}+\\dfrac{1}{3a_3}+\\dots+\\dfrac{1}{2020a_{2020}}=1.$$', 'We show the following is true:\\begin{claim}The set of numbers $a_i=\\begin{cases}n\\text{ if }i=1\\\\i-1\\text{ if }i>1\\end{cases}$ for $1\\le i\\le n$ satisfies $$\\sum^n_{i=1}\\frac1{ia_i}=1$$ for all $n\\in\\mathbb N.$ \\end{claim}\\begin{proof}We have \\begin{align*}\\sum^n_{i=1}\\frac1{ia_i}&=\\frac1n+\\sum^n_{i=2}\\frac1{i(i-1)}\\\\&=\\frac1n+\\sum^n_{i=2}\\left(\\frac{1}{i-1}-\\frac1{i}\\right)\\\\&=\\frac1n+\\left(1-\\frac1{n}\\right)=1.\\end{align*}\\end{proof}Thus, with the given, $a_i=\\begin{cases}2020~\\text{if}~i=1\\\\i-1~\\text{if}~i>1\\end{cases},$ so there exists positive integers $a_1,a_2,a_3,\\dots,a_{2020}$ such that $$\\dfrac{1}{a_1}+\\dfrac{1}{2a_2}+\\dfrac{1}{3a_3}+\\dots+\\dfrac{1}{2020a_{2020}}=1.$$ $\\square$'],
    [1, 'C', 'S', 'Paraguay 2015 / 1', 'Alexa wrote the first 16 numbers of a sequence: \\begin{equation*}1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8, 9, 10, 10, 11, \\dots\\end{equation*} Then she continued following the same pattern, until she had 2015 numbers in total. What was the last number she wrote?', '1344'],
    [2, 'A', 'S', 'AHSME 1978 / 11\\footnote{Modified to fit for short answer.}', 'If $r$ is positive and the line whose equation is $x + y = r$ is tangent to the circle whose equation is $x^2 + y ^2 = r$, then what is the value of $r$?', '2'],
    [3, 'C', 'S', 'AMC 12 2019 / 9', 'A sequence of numbers is defined recursively by $a_1 = 1$, $a_2 = \\frac{3}{7}$, and\\[a_n=\\frac{a_{n-2} \\cdot a_{n-1}}{2a_{n-2} - a_{n-1}}\\]for all $n \\geq 3$. Then $a_{2019}$ can be written as $\\frac{p}{q}$, where $p$ and $q$ are relatively prime positive integers. What is $p+q ?$', '8078'],
    [2, 'C', 'S', 'PMO 2024 Qualifying / II.6', 'Eight people are to sit around a round table on equally-spaced seats. Two of the eight people, Alice and Bob, insist on sitting next to each other. Meanwhile, another two, Clara and Dan, insist on sitting opposite each other. How many ways are there to seat the eight people? Rotations are considered equivalent.', '192'],
    [2, 'C', 'S', 'PMO 2024 Qualifying / II.7', 'A finite sequence $a_1,a_2,\\dots,a_n$, with $n\\ge3$, is said to be \\textit{strongly unimodal} if ther exists an integer $k$, with $1<k<n$, such that $a_1<\\dots<a_k>a_{k+1}>\\dots>a_n$. How many strongly unimodal sequences $a_1,\\dots,a_{26}$ are there which are permutations of the set $\{1,2,\\dots,26\}$?', '$2^25-2$'],
    [2, 'G', 'S', 'PMO 2024 Qualifying / II.8\\footnote{Modified diagram.}', 'A square of side length 1 and a rectangle of length 34 are inscribed in a semicircle as shown below. What is the area of the rectangle?\n\\begin{center}\n\\begin{asy}\nimport graph; size(7.6cm); real lsf=0.5; pen dps=linewidth(0.7)+fontsize(10); defaultpen(dps); pen ds=black; real xmin=-3.,xmax=35.,ymin=-7.,ymax=13.; draw((-2.,-6.)--(-1.,-6.)--(-1.,-5.)--(-2.,-5.)--cycle,linewidth(1)); draw((-1.,-6.)--(-1.,0.)--(33.,0.)--(33.,-6.)--cycle,linewidth(1)); draw((-2.,-6.)--(-1.,-6.),linewidth(1)); draw((-1.,-6.)--(-1.,-5.),linewidth(1)); draw((-1.,-5.)--(-2.,-5.),linewidth(1)); draw((-2.,-5.)--(-2.,-6.),linewidth(1)); draw((-1.,-6.)--(-1.,0.),linewidth(1)); draw((-1.,0.)--(33.,0.),linewidth(1)); draw((33.,0.)--(33.,-6.),linewidth(1)); draw((33.,-6.)--(-1.,-6.),linewidth(1)); draw(shift((16.,-6.))*xscale(18.027756377319946)*yscale(18.027756377319946)*arc((0,0),1,0.,180.),linewidth(1)); draw((-2.0277563773199496,-6.)--(34.027756377319946,-6.),linewidth(1)); clip((xmin,ymin)--(xmin,ymax)--(xmax,ymax)--(xmax,ymin)--cycle);\n\\end{asy}\n\\end{center}', '204'],
    [2, 'C', 'S', 'PMO 2024 Qualifying / II.9', 'A palindrome is a number that reads the same backward and forward. If a palindrome between 100 and 1000 (inclusive) is chosen uniformly at random, what is the probability that this number is divisible by 11?', '$\\frac{4}{45}$'],
    [3, 'C', 'S', 'PMO 2024 Qualifying / II.10', 'Ernest has a jar with 26 identical cookies. He wants to finish the cookies in the jar by eating 2 or 3 cookies each day. In how many ways can he do this?', '616'],
    [0, 'A', 'S', 'Australian MC 2016 I / 1', 'What is the value of $20\\times16$?', '320'],
    [0, 'A', 'S', 'Australian MC 2016 I / 2\\footnote{Modified wording and diagram.}', 'In the figure, the unlabeled region is what fraction of the circle? \n\\begin{center}\n\\begin{asy}\nimport graph; usepackage("amsmath"); size(5cm); real lsf=0.5; pen dps=linewidth(0.7)+fontsize(10); defaultpen(dps); pen ds=black; real xmin=-7.22,xmax=7.94,ymin=-7.24,ymax=11.52; draw(circle((0.,4.),4.),linewidth(2.)); draw((0.,4.)--(1.2360679774997898,0.19577393481938588),linewidth(2.)); draw((0.,4.)--(0.,0.),linewidth(2.)); draw((0.,4.)--(-4.,4.),linewidth(2.)); draw((0.,4.)--(4.,4.),linewidth(2.)); draw(shift((0.,4.))*xscale(4.)*yscale(4.)*arc((0,0),1,270.,288.)--(0.,4.)--cycle,linewidth(2.)); label("$\dfrac12$",(-0.24,6.92),SE*lsf); label("$\dfrac14$",(-2.02,3.20),SE*lsf); label("$\dfrac15$",(1.78,3.20),SE*lsf); clip((xmin,ymin)--(xmin,ymax)--(xmax,ymax)--(xmax,ymin)--cycle);\n\\end{asy}\n\\end{center}', '$\\frac1{20}$'],
    [0, 'A', 'S', 'Australian MC 2016 I / 3\\footnote{Modified to fit for short answer.}', 'The cycling road race through the Adelaide Hills started at 11:15 am and the winner finished at 2:09 pm the same day. What is the winner\'s time in minutes?', '174'],
    [0, 'N', 'S', 'Australian MC 2016 I / 4\\footnote{Modified to fit for short answer.}', 'The fraction $\\frac{720163}{2016}$ is between which two powers of 10? (Give the numbers themselves and not the exponents.)', '100 and 1000'],
    [0, 'A', 'S', 'Australian MC 2016 I / 5', 'What is the value of $(1\\div2)\\div(3\\div4)$?', '$\\frac23$'],
    [0, 'A', 'S', 'Australian MC 2016 I / 6\\footnote{Modified to fit for short answer.}', '$0.75\\%$ of a number is $6$. What is the number?', '800'],
    [1, 'A', 'S', 'Australian MC 2016 I / 7', 'In the expression below, the letters $A,B,C,D,$ and $E$ represent the numbers $1,2,3,4,$ and $5$ in some order. $$A\\times B+C\\times D+E$$ What is the largest value of the expression?', '27'],
    [1, 'G', 'S', 'Australian MC 2016 I / 8\\footnote{Modified without diagram.}', 'Consider the descriptions of four squares P, Q, R, and S as follows.\n\\begin{itemize}\n\\item In square P, the distance between the center and a vertex is 1 unit.\n\\item In square Q, the distance between the center and a side is 1 unit.\n\\item In square R, the distance between two opposite vertices is 1 unit.\n\\item In square S, the side length is 1 unit.\n\\end{itemize}\nWhich of the squares would have the greatest perimeter?', 'Q'],
    [1, 'G', 'S', 'Australian MC 2016 I / 9\\footnote{Modified without diagram and to fit for short answer.}', 'On a clock face, a line is drawn between 9 and 3 and another between 12 and 8. What is the acute angle between these lines in degrees?', '$60^\circ$'],
    [1, 'C', 'S', 'Australian MC 2016 I / 10', 'There are 3 blue pens, 4 red pens and 5 yellow pens in a box. Without looking, I take pens from the box one by one. How many pens do I need to take from the box to be certain that I have at least one pen of each colour?', '10'],
    [2, 'N', 'S', 'Australian MC 2018 S / 26 (J / 30)', 'Let $A$ be a 2018-digit number which is divisible by 9. Let $B$ be the sum of all digits of $A$ and $C$ be the sum of all digits of $B$. Find the sum of all possible values of $C$.', '90'],
    [2, 'C', 'S', 'Australian MC 2019 I / 26 (J / 27)', 'A positive whole number is called stable if at least one of its digits has the same value as its position in the number. For example, 78247 is stable because a 4 appears in the $4^{\text{th}}$ position. How many stable 3-digit numbers are there?', '252'],
    [3, 'N', 'S', 'Australian MC 2019 S / 27 (J / 29)', 'In a list of numbers, an odd-sum triple is a group of three numbers in a row that add to an odd number. For instance, if we write the numbers from 1 to 6 in this order, $$6\\qquad4\\qquad2\\qquad1\\qquad3\\qquad5$$ then there are exactly two odd-sum triples: $(4, 2, 1)$ and $(1, 3, 5)$. What is the greatest number of odd-sum triples that can be made by writing the numbers from 1 to 1000 in some order?', '997'],
    [3, 'C', 'S', 'Australian MC 2016 S / 29 (I / 30)', 'Around a circle, I place 64 equally spaced points, so that there are $64\\times63\\div2 = 2016$ possible chords between these points. I draw some of these chords, but each chord cannot cut across more than one other chord. What is the maximum number of chords I can draw?', '156']
    ]